# Material Palenight Theme for Alacritty

[colors.primary]
background = "#292d3e"
foreground = "#a6accd"

[colors.normal]
black = "#292d3e"
red = "#f07178"
green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#89ddff"
white = "#d0d0d0"

[colors.bright]
black = "#434758"
red = "#f07178"
green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#89ddff"
white = "#d0d0d0"
